name: spin
channels:
    - conda-forge/label/cf201901
    - anaconda
    - conda-forge
    - defaults
dependencies:
    - siesta==4.1.5
    - matplotlib==3.4.3
    - numpy==1.21.2
    - pandas==1.3.2
    - ase==3.22.0
    - openbabel==3.1.1
    - ipysheet==0.5.0
    - ipywidgets==7.5.1
    - py3dmol==1.7.0
    - nglview==3.0.3
    - ipyfilechooser==0.6.0
    - openpyxl
    - pip
    - pip:
        - html2image==2.0.1